# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'corry.ui'
#
# Created: Fri May  1 14:09:21 2020
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(550, 563)
        Dialog.setStyleSheet(_fromUtf8("QDialog {\n"
"    background-color: white;\n"
"}"))
        self.countryFlag = QtGui.QLabel(Dialog)
        self.countryFlag.setGeometry(QtCore.QRect(20, 10, 250, 167))
        self.countryFlag.setStyleSheet(_fromUtf8("#countryFlag {\n"
"    border-radius: 20px;\n"
"    color:red;\n"
"}"))
        self.countryFlag.setText(_fromUtf8(""))
        self.countryFlag.setPixmap(QtGui.QPixmap(_fromUtf8("images/custom – 1.jpg")))
        self.countryFlag.setObjectName(_fromUtf8("countryFlag"))
        self.bg = QtGui.QFrame(Dialog)
        self.bg.setGeometry(QtCore.QRect(20, 200, 511, 331))
        self.bg.setStyleSheet(_fromUtf8("#bg {\n"
"    background-color: rgb(71,63,151);\n"
"border-radius: 20px\n"
"        \n"
"}"))
        self.bg.setFrameShape(QtGui.QFrame.StyledPanel)
        self.bg.setFrameShadow(QtGui.QFrame.Raised)
        self.bg.setObjectName(_fromUtf8("bg"))
        self.frame_recovered = QtGui.QFrame(self.bg)
        self.frame_recovered.setGeometry(QtCore.QRect(20, 170, 151, 141))
        self.frame_recovered.setStyleSheet(_fromUtf8("#frame_recovered {\n"
"background-color: rgb(76, 217, 123);\n"
"    border-radius: 20px;\n"
"}\n"
""))
        self.frame_recovered.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_recovered.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_recovered.setObjectName(_fromUtf8("frame_recovered"))
        self.recovered = QtGui.QLabel(self.frame_recovered)
        self.recovered.setGeometry(QtCore.QRect(20, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Montserrat"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recovered.setFont(font)
        self.recovered.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.recovered.setObjectName(_fromUtf8("recovered"))
        self.recoveredCount = QtGui.QLabel(self.frame_recovered)
        self.recoveredCount.setGeometry(QtCore.QRect(10, 90, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Montserrat"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.recoveredCount.setFont(font)
        self.recoveredCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.recoveredCount.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.recoveredCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.recoveredCount.setObjectName(_fromUtf8("recoveredCount"))
        self.frame_affected = QtGui.QFrame(self.bg)
        self.frame_affected.setGeometry(QtCore.QRect(20, 20, 231, 141))
        self.frame_affected.setStyleSheet(_fromUtf8("#frame_affected {\n"
"    background-color: #FFB259;\n"
"    border-radius: 20px;\n"
"}"))
        self.frame_affected.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_affected.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_affected.setObjectName(_fromUtf8("frame_affected"))
        self.confirmed = QtGui.QLabel(self.frame_affected)
        self.confirmed.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Montserrat"))
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.confirmed.setFont(font)
        self.confirmed.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.confirmed.setObjectName(_fromUtf8("confirmed"))
        self.confirmedCount = QtGui.QLabel(self.frame_affected)
        self.confirmedCount.setGeometry(QtCore.QRect(20, 80, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Montserrat"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.confirmedCount.setFont(font)
        self.confirmedCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.confirmedCount.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.confirmedCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.confirmedCount.setObjectName(_fromUtf8("confirmedCount"))
        self.frame_deaths = QtGui.QFrame(self.bg)
        self.frame_deaths.setGeometry(QtCore.QRect(260, 20, 231, 141))
        self.frame_deaths.setStyleSheet(_fromUtf8("background-color: rgb(255, 89, 89);\n"
"    border-radius: 20px;"))
        self.frame_deaths.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_deaths.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_deaths.setObjectName(_fromUtf8("frame_deaths"))
        self.deaths = QtGui.QLabel(self.frame_deaths)
        self.deaths.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Montserrat"))
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.deaths.setFont(font)
        self.deaths.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.deaths.setObjectName(_fromUtf8("deaths"))
        self.deathsCount = QtGui.QLabel(self.frame_deaths)
        self.deathsCount.setGeometry(QtCore.QRect(20, 80, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Montserrat"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.deathsCount.setFont(font)
        self.deathsCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.deathsCount.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.deathsCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.deathsCount.setObjectName(_fromUtf8("deathsCount"))
        self.frame_active = QtGui.QFrame(self.bg)
        self.frame_active.setGeometry(QtCore.QRect(180, 170, 151, 141))
        self.frame_active.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(76, 181, 255);\n"
"    border-radius: 20px;"))
        self.frame_active.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_active.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_active.setObjectName(_fromUtf8("frame_active"))
        self.active = QtGui.QLabel(self.frame_active)
        self.active.setGeometry(QtCore.QRect(20, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Montserrat"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.active.setFont(font)
        self.active.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.active.setObjectName(_fromUtf8("active"))
        self.activeCount = QtGui.QLabel(self.frame_active)
        self.activeCount.setGeometry(QtCore.QRect(10, 90, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Montserrat"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.activeCount.setFont(font)
        self.activeCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.activeCount.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.activeCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.activeCount.setObjectName(_fromUtf8("activeCount"))
        self.frame_critical = QtGui.QFrame(self.bg)
        self.frame_critical.setGeometry(QtCore.QRect(340, 170, 151, 141))
        self.frame_critical.setStyleSheet(_fromUtf8("background-color: rgb(144, 89, 255);\n"
"    border-radius: 20px;"))
        self.frame_critical.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_critical.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_critical.setObjectName(_fromUtf8("frame_critical"))
        self.critical = QtGui.QLabel(self.frame_critical)
        self.critical.setGeometry(QtCore.QRect(20, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Montserrat"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.critical.setFont(font)
        self.critical.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.critical.setObjectName(_fromUtf8("critical"))
        self.criticalCount = QtGui.QLabel(self.frame_critical)
        self.criticalCount.setGeometry(QtCore.QRect(10, 90, 131, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Montserrat"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.criticalCount.setFont(font)
        self.criticalCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.criticalCount.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.criticalCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.criticalCount.setObjectName(_fromUtf8("criticalCount"))
        self.coronavirus = QtGui.QLabel(Dialog)
        self.coronavirus.setGeometry(QtCore.QRect(350, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Montserrat Black"))
        font.setPointSize(20)
        font.setItalic(True)
        self.coronavirus.setFont(font)
        self.coronavirus.setStyleSheet(_fromUtf8("color: rgb(143, 143, 143);"))
        self.coronavirus.setObjectName(_fromUtf8("coronavirus"))
        self.covid19 = QtGui.QLabel(Dialog)
        self.covid19.setGeometry(QtCore.QRect(350, 40, 181, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Montserrat Black"))
        font.setPointSize(26)
        font.setItalic(True)
        self.covid19.setFont(font)
        self.covid19.setStyleSheet(_fromUtf8("color: rgb(206, 0, 0);"))
        self.covid19.setObjectName(_fromUtf8("covid19"))
        self.country = QtGui.QLineEdit(Dialog)
        self.country.setGeometry(QtCore.QRect(300, 109, 221, 31))
        self.country.setStyleSheet(_fromUtf8("border-color: rgb(143, 143, 143);"))
        self.country.setObjectName(_fromUtf8("country"))
        self.selectCountry = QtGui.QLabel(Dialog)
        self.selectCountry.setGeometry(QtCore.QRect(300, 80, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Montserrat Black"))
        font.setPointSize(11)
        font.setItalic(True)
        self.selectCountry.setFont(font)
        self.selectCountry.setStyleSheet(_fromUtf8("color: rgb(143, 143, 143);"))
        self.selectCountry.setObjectName(_fromUtf8("selectCountry"))
        self.logo = QtGui.QLabel(Dialog)
        self.logo.setGeometry(QtCore.QRect(340, 530, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Montserrat Black"))
        font.setPointSize(9)
        font.setItalic(False)
        self.logo.setFont(font)
        self.logo.setStyleSheet(_fromUtf8("color: rgb(143, 143, 143);"))
        self.logo.setObjectName(_fromUtf8("logo"))
        self.lastUpdated = QtGui.QLabel(Dialog)
        self.lastUpdated.setGeometry(QtCore.QRect(300, 140, 221, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Montserrat Medium"))
        font.setPointSize(8)
        font.setItalic(False)
        font.setKerning(True)
        self.lastUpdated.setFont(font)
        self.lastUpdated.setStyleSheet(_fromUtf8("color: rgb(143, 143, 143);"))
        self.lastUpdated.setObjectName(_fromUtf8("lastUpdated"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.recovered.setText(_translate("Dialog", "Recovered", None))
        self.recoveredCount.setText(_translate("Dialog", "0", None))
        self.confirmed.setText(_translate("Dialog", "Confirmed", None))
        self.confirmedCount.setText(_translate("Dialog", "0", None))
        self.deaths.setText(_translate("Dialog", "Deaths", None))
        self.deathsCount.setText(_translate("Dialog", "0", None))
        self.active.setText(_translate("Dialog", "Active", None))
        self.activeCount.setText(_translate("Dialog", "0", None))
        self.critical.setText(_translate("Dialog", "Critical", None))
        self.criticalCount.setText(_translate("Dialog", "0", None))
        self.coronavirus.setText(_translate("Dialog", "Coronavirus", None))
        self.covid19.setText(_translate("Dialog", "COVID-19", None))
        self.selectCountry.setText(_translate("Dialog", "Search Country", None))
        self.logo.setText(_translate("Dialog", "Designed by: Prince Radebe", None))
        self.lastUpdated.setText(_translate("Dialog", "last updated: 01-May-2020", None))

